os: Visual Studio 2015
environment:
  snk_secret:
    secure: 0l0TrDvCNXH4z922G/Qa5hFG4+4payl1zRAfjMfEXRw=

install:
  - dnvm install latest
  - dnu restore --quiet
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt NGettext.snk.enc -secret %snk_secret%

build:
  project: NGettext.sln

test_script:
  - cd test\NGettext.Tests
  - dnx test
  - cd ..\..
  - cd test\NGettext.PluralCompile.Tests
  - dnx test
